version: "3"
services:
  securityc:
    image: securityc:0.0.0j
    environment:
      - SECURITYC_SERVER_CA_COMMON_NAME=bpanel
      - SECURITYC_SERVER_CERT_COMMON_NAME=localhost
      - SECURITYC_SERVER_CERT_IP=127.0.0.1
      - SECURITYC_SERVER_CERT_DOMAIN=localhost
      - SECURITYC_SERVER_CA_OUT=/etc/ssl/certs/ca.crt
      # nginx config knows to look in /etc/nginx
      - SECURITYC_SERVER_KEY_OUT=/etc/nginx/tls.key
      - SECURITYC_SERVER_CERT_OUT=/etc/nginx/tls.crt
    volumes:
      # expose ca cert to the user
      - ./:/etc/ssl/certs
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/mime.types:/etc/nginx/mime.types:ro
    ports:
      - "80:80"
      - "4443:4443"
  server:
    image: node:8
    command: ["node", "/app/server.js"]
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PORT=5000
  client:
    image: ubuntu-openssl:0.0.35
    command: ["bash", "-c", "while true; do sleep 10; done"]
